#!/bin/sh

### BEGIN INIT INFO
# Provides:          meniscus-portal
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Project Meniscus node daemon.
# Description:       Project Meniscus is a Python based system for event collection, transit and
#                    processing in the large. It's primary use case is for large-scale Cloud
#                    logging, but can be used in many other scenarios including usage reporting
#                    and API tracing.
### END INIT INFO

# Author: John Hopper <john.hopper@rackspace.com>

set -e

NAME=meniscus-portal
PIDFILE=/var/run/${NAME}.pid
DAEMON="/usr/bin/${NAME}"
DAEMON_OPTS=""
USER=${NAME}
APPDIR=/var/lib/${NAME}

PATH=/sbin:/usr/sbin:/bin:/usr/bin

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
        start-stop-daemon --start --background --chdir $APPDIR --quiet --chuid $USER --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "."
    ;;
  stop)
        echo -n "Stopping daemon: "$NAME
        start-stop-daemon --stop --chdir $APPDIR --quiet --chuid $USER --oknodo --pidfile $PIDFILE
        echo "."
    ;;
  restart)
        echo -n "Restarting daemon: "$NAME
        start-stop-daemon --stop --chdir $APPDIR --quiet --chuid $USER --oknodo --retry 30 --pidfile $PIDFILE
        start-stop-daemon --start --background --chdir $APPDIR --quiet --chuid $USER --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "."
    ;;

  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
esac

exit 0
