#!/bin/sh
# postrm script for meniscus-portal
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    purge)
        echo "Purging meniscus-portal..." >&2
        if (getent passwd meniscus-portal) > /dev/null 2>&1; then
            userdel meniscus-portal || true
        fi

        if (getent group meniscus-portal) > /dev/null 2>&1; then
            groupdel meniscus-portal || true
        fi

        [ -e /var/lib/meniscus-portal ] && rm -rf /var/lib/meniscus-portal
        [ -e /var/log/meniscus-portal ] && rm -rf /var/log/meniscus-portal
        [ -e /usr/share/meniscus-portal ] && rm -rf /usr/share/meniscus-portal
        [ -e /etc/meniscus-portal ] && rm -rf /etc/meniscus-portal
    ;;

    upgrade|failed-upgrade|abort-upgrade)
        echo "upgrade ignored, yo"
    ;;

    remove|abort-install|disappear)
        [ -e /usr/share/meniscus-portal ] && rm -rf /usr/share/meniscus-portal
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
