#!/bin/sh
# postinst script for meniscus-portal
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
        . /usr/share/debconf/confmodule

        if ! (getent group meniscus-portal) > /dev/null 2>&1; then
            addgroup --quiet --system meniscus-portal > /dev/null
        fi

        if ! (getent passwd meniscus-portal) > /dev/null 2>&1; then
            adduser --quiet --system --home /var/lib/meniscus-portal --ingroup meniscus-portal --no-create-home --shell /bin/false meniscus-portal
        fi

        chmod 0755 /etc/init.d/meniscus-portal

        if [ ! -d /var/log/meniscus-portal ]; then
            mkdir /var/log/meniscus-portal
            chown -R meniscus-portal:adm /var/log/meniscus-portal/
            chmod 0750 /var/log/meniscus-portal/
        fi

        if [ ! -d /var/lib/meniscus-portal ]; then
            mkdir /var/lib/meniscus-portal
            chown meniscus-portal:meniscus-portal -R /var/lib/meniscus-portal/ /etc/meniscus-portal
            chmod -R 0700 /etc/meniscus-portal/
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
